export const CATEGORY_LABELS: Record<string, string> = {
	"cs.AI": "Artificial Intelligence",
	"cs.AR": "Hardware Architecture",
	"cs.CC": "Computational Complexity",
	"cs.CE": "Computational Engineering, Finance & Science",
	"cs.CG": "Computational Geometry",
	"cs.CL": "Computation and Language",
	"cs.CR": "Cryptography and Security",
	"cs.CV": "Computer Vision and Pattern Recognition",
	"cs.CY": "Computers and Society",
	"cs.DB": "Databases",
	"cs.DC": "Distributed, Parallel, and Cluster Computing",
	"cs.DL": "Digital Libraries",
	"cs.DM": "Discrete Mathematics",
	"cs.DS": "Data Structures and Algorithms",
	"cs.ET": "Emerging Technologies",
	"cs.FL": "Formal Languages and Automata Theory",
	"cs.GL": "General Literature",
	"cs.GR": "Computer Graphics",
	"cs.GT": "Computer Science and Game Theory",
	"cs.HC": "Human-Computer Interaction",
	"cs.IR": "Information Retrieval",
	"cs.IT": "Information Theory",
	"cs.LG": "Machine Learning",
	"cs.LO": "Logic in Computer Science",
	"cs.MA": "Multiagent Systems",
	"cs.MM": "Multimedia",
	"cs.MS": "Mathematical Software",
	"cs.NA": "Numerical Analysis",
	"cs.NE": "Neural and Evolutionary Computing",
	"cs.NI": "Networking and Internet Architecture",
	"cs.OH": "Other Computer Science",
	"cs.OS": "Operating Systems",
	"cs.PF": "Performance",
	"cs.PL": "Programming Languages",
	"cs.RO": "Robotics",
	"cs.SC": "Symbolic Computation",
	"cs.SD": "Sound",
	"cs.SE": "Software Engineering",
	"cs.SI": "Social and Information Networks",
	"cs.SY": "Systems and Control",
	"math.MP": "Mathematical Physics",
	"math.CO": "Combinatorics",
	"math.AP": "Analysis of PDEs",
	"math.PR": "Probability",
	"math.OC": "Optimization and Control",
	"math.AG": "Algebraic Geometry",
	"math.NT": "Number Theory",
	"math.DG": "Differential Geometry",
	"math.DS": "Dynamical Systems",
	"math.FA": "Functional Analysis",
	"math.RT": "Representation Theory",
	"math.ST": "Statistics Theory",
	"math.GT": "Geometric Topology",
	"math.GR": "Group Theory",
	"math.CA": "Classical Analysis and ODEs",
	"math.QA": "Quantum Algebra",
	"math.RA": "Rings and Algebras",
	"math.CV": "Complex Variables",
	"math.AT": "Algebraic Topology",
	"math.LO": "Logic",
	"math.AC": "Commutative Algebra",
	"math.OA": "Operator Algebras",
	"math.MG": "Metric Geometry",
	"math.SP": "Spectral Theory",
	"math.SG": "Symplectic Geometry",
	"math.CT": "Category Theory",
	"math.KT": "K-Theory and Homology",
	"math.GN": "General Topology",
	"math.GM": "General Mathematics",
	"math.HO": "History and Overview",
	"cond-mat.mtrl-sci": "Materials Science",
	"cond-mat.mes-hall": "Mesoscale and Nanoscale Physics",
	"cond-mat.str-el": "Strongly Correlated Electrons",
	"cond-mat.stat-mech": "Statistical Mechanics",
	"cond-mat.supr-con": "Superconductivity",
	"cond-mat.soft": "Soft Condensed Matter",
	"cond-mat.dis-nn": "Disordered Systems and Neural Networks",
	"cond-mat.quant-gas": "Quantum Gases",
	"cond-mat.other": "Other Condensed Matter",
	"astro-ph.GA": "Galactic Astrophysics",
	"astro-ph.CO": "Cosmology and Nongalactic Astrophysics",
	"astro-ph.SR": "Solar and Stellar Astrophysics",
	"astro-ph.HE": "High-Energy Astrophysical Phenomena",
	"astro-ph.IM": "Instrumentation and Methods for Astrophysics",
	"astro-ph.EP": "Earth and Planetary Astrophysics",
	"physics.optics": "Optics",
	"physics.flu-dyn": "Fluid Dynamics",
	"physics.comp-ph": "Computational Physics",
	"physics.chem-ph": "Chemical Physics",
	"physics.soc-ph": "Physics and Society",
	"physics.ins-det": "Instrumentation and Detectors",
	"physics.atom-ph": "Atomic Physics",
	"physics.app-ph": "Applied Physics",
	"physics.plasm-ph": "Plasma Physics",
	"physics.bio-ph": "Biological Physics",
	"physics.data-an": "Data Analysis, Statistics and Probability",
	"physics.gen-ph": "General Physics",
	"physics.class-ph": "Classical Physics",
	"physics.med-ph": "Medical Physics",
	"physics.acc-ph": "Accelerator Physics",
	"physics.geo-ph": "Geophysics",
	"physics.ao-ph": "Atmospheric and Oceanic Physics",
	"physics.space-ph": "Space Physics",
	"physics.hist-ph": "History and Philosophy of Physics",
	"physics.ed-ph": "Physics Education",
	"physics.atm-clus": "Atomic and Molecular Clusters",
	"physics.pop-ph": "Popular Physics",
	"stat.ML": "Machine Learning",
	"stat.ME": "Methodology",
	"stat.TH": "Statistics Theory",
	"stat.AP": "Applications",
	"stat.CO": "Computation",
	"stat.OT": "Other Statistics",
	"eess.SP": "Signal Processing",
	"eess.SY": "Systems and Control",
	"eess.IV": "Image and Video Processing",
	"eess.AS": "Audio and Speech Processing",
	"q-bio.QM": "Quantitative Methods",
	"q-bio.PE": "Populations and Evolution",
	"q-bio.NC": "Neurons and Cognition",
	"q-bio.BM": "Biomolecules",
	"q-bio.MN": "Molecular Networks",
	"q-bio.GN": "Genomics",
	"q-bio.TO": "Tissues and Organs",
	"q-bio.CB": "Cell Behavior",
	"q-bio.SC": "Subcellular Processes",
	"q-bio.OT": "Other Quantitative Biology",
	"nlin.CD": "Chaotic Dynamics",
	"nlin.SI": "Exactly Solvable and Integrable Systems",
	"nlin.PS": "Pattern Formation and Solitons",
	"nlin.AO": "Adaptation and Self-Organizing Systems",
	"nlin.CG": "Cellular Automata and Lattice Gases",
	"q-fin.EC": "Economics",
	"q-fin.ST": "Statistical Finance",
	"q-fin.MF": "Mathematical Finance",
	"q-fin.CP": "Computational Finance",
	"q-fin.GN": "General Finance",
	"q-fin.RM": "Risk Management",
	"q-fin.PM": "Portfolio Management",
	"q-fin.PR": "Pricing of Securities",
	"q-fin.TR": "Trading and Market Microstructure",
	"econ.GN": "General Economics",
	"econ.EM": "Econometrics",
	"econ.TH": "Economic Theory",
	"hep-ph": "High-Energy Physics — Phenomenology",
	"hep-th": "High-Energy Physics — Theory",
	"quant-ph": "Quantum Physics",
	"gr-qc": "General Relativity and Quantum Cosmology",
	"nucl-th": "Nuclear Theory",
	"nucl-ex": "Nuclear Experiment",
	"hep-ex": "High-Energy Physics — Experiment",
	"hep-lat": "High-Energy Physics — Lattice",
};

export function categoryLabel(id: string): string {
	return CATEGORY_LABELS[id] ?? id;
}
