CATEGORY_LABELS = {
    "cs.AI": "Computer Science - Artificial Intelligence",
    "cs.AR": "Computer Science - Architecture",
    "cs.CC": "Computer Science - Computational Complexity",
    "cs.CE": "Computer Science - Computational Engineering",
    "cs.CG": "Computer Science - Computational Geometry",
    "cs.CL": "Computer Science - Computation & Language",
    "cs.CR": "Computer Science - Cryptography & Security",
    "cs.CV": "Computer Science - Computer Vision",
    "cs.CY": "Computer Science - Computers & Society",
    "cs.DB": "Computer Science - Databases",
    "cs.DC": "Computer Science - Distributed Computing",
    "cs.DL": "Computer Science - Digital Libraries",
    "cs.DS": "Computer Science - Data Structures & Algorithms",
    "cs.ET": "Computer Science - Emerging Technologies",
    "cs.FL": "Computer Science - Formal Languages & Automata",
    "cs.GL": "Computer Science - General Literature",
    "cs.GR": "Computer Science - Graphics",
    "cs.GT": "Computer Science - Game Theory",
    "cs.HC": "Computer Science - Human-Computer Interaction",
    "cs.IR": "Computer Science - Information Retrieval",
    "cs.IT": "Computer Science - Information Theory",
    "cs.LG": "Computer Science - Machine Learning",
    "cs.LO": "Computer Science - Logic",
    "cs.MA": "Computer Science - Multiagent Systems",
    "cs.MM": "Computer Science - Multimedia",
    "cs.MS": "Computer Science - Mathematical Software",
    "cs.NA": "Computer Science - Numerical Analysis",
    "cs.NE": "Computer Science - Neural & Evolutionary Computing",
    "cs.NI": "Computer Science - Networking & Internet",
    "cs.OH": "Computer Science - Other",
    "cs.OS": "Computer Science - Operating Systems",
    "cs.PF": "Computer Science - Performance",
    "cs.PL": "Computer Science - Programming Languages",
    "cs.RO": "Computer Science - Robotics",
    "cs.SC": "Computer Science - Symbolic Computation",
    "cs.SD": "Computer Science - Sound",
    "cs.SE": "Computer Science - Software Engineering",
    "cs.SI": "Computer Science - Social & Information Networks",
    "cs.SY": "Computer Science - Systems & Control",
    "math.AG": "Mathematics - Algebraic Geometry",
    "math.AP": "Mathematics - Analysis of PDEs",
    "math.AT": "Mathematics - Algebraic Topology",
    "math.CA": "Mathematics - Classical Analysis & ODEs",
    "math.CO": "Mathematics - Combinatorics",
    "math.CT": "Mathematics - Category Theory",
    "math.CV": "Mathematics - Complex Variables",
    "math.DG": "Mathematics - Differential Geometry",
    "math.DS": "Mathematics - Dynamical Systems",
    "math.FA": "Mathematics - Functional Analysis",
    "math.GM": "Mathematics - General Mathematics",
    "math.GN": "Mathematics - General Topology",
    "math.GR": "Mathematics - Group Theory",
    "math.GT": "Mathematics - Geometric Topology",
    "math.HO": "Mathematics - History & Overview",
    "math.IT": "Mathematics - Information Theory",
    "math.KT": "Mathematics - K-Theory & Homology",
    "math.LO": "Mathematics - Logic",
    "math.MG": "Mathematics - Metric Geometry",
    "math.MP": "Mathematics - Mathematical Physics",
    "math.NA": "Mathematics - Numerical Analysis",
    "math.NT": "Mathematics - Number Theory",
    "math.OA": "Mathematics - Operator Algebras",
    "math.OC": "Mathematics - Optimization & Control",
    "math.PR": "Mathematics - Probability",
    "math.QA": "Mathematics - Quantum Algebra",
    "math.RA": "Mathematics - Rings & Algebras",
    "math.RT": "Mathematics - Representation Theory",
    "math.SG": "Mathematics - Symplectic Geometry",
    "math.SP": "Mathematics - Spectral Theory",
    "math.ST": "Mathematics - Statistics",
    "astro-ph": "Astrophysics",
    "astro-ph.CO": "Astrophysics - Cosmology",
    "astro-ph.EP": "Astrophysics - Earth & Planetary Astrophysics",
    "astro-ph.GA": "Astrophysics - Astrophysics of Galaxies",
    "astro-ph.HE": "Astrophysics - High Energy Astrophysical Phenomena",
    "astro-ph.IM": "Astrophysics - Instrumentation & Methods",
    "astro-ph.SR": "Astrophysics - Solar & Stellar Astrophysics",
    "cond-mat": "Condensed Matter",
    "cond-mat.dis-nn": "Condensed Matter - Disordered Systems & Neural Networks",
    "cond-mat.mes-hall": "Condensed Matter - Mesoscale & Nanoscale Physics",
    "cond-mat.mtrl-sci": "Condensed Matter - Materials Science",
    "cond-mat.other": "Condensed Matter - Other",
    "cond-mat.quant-gas": "Condensed Matter - Quantum Gases",
    "cond-mat.soft": "Condensed Matter - Soft Condensed Matter",
    "cond-mat.stat-mech": "Condensed Matter - Statistical Mechanics",
    "cond-mat.str-el": "Condensed Matter - Strongly Correlated Electrons",
    "cond-mat.supr-con": "Condensed Matter - Superconductivity",
    "hep-ex": "High Energy Physics - Experiment",
    "hep-lat": "High Energy Physics - Lattice",
    "hep-ph": "High Energy Physics - Phenomenology",
    "hep-th": "High Energy Physics - Theory",
    "gr-qc": "General Relativity & Quantum Cosmology",
    "quant-ph": "Quantum Physics",
    "nucl-ex": "Nuclear Experiment",
    "nucl-th": "Nuclear Theory",
    "physics.acc-ph": "Physics - Accelerator Physics",
    "physics.ao-ph": "Physics - Atmospheric & Oceanic Physics",
    "physics.atm-clus": "Physics - Atomic & Molecular Clusters",
    "physics.atom-ph": "Physics - Atomic Physics",
    "physics.bio-ph": "Physics - Biological Physics",
    "physics.chem-ph": "Physics - Chemical Physics",
    "physics.class-ph": "Physics - Classical Physics",
    "physics.comp-ph": "Physics - Computational Physics",
    "physics.data-an": "Physics - Data Analysis, Statistics & Probability",
    "physics.ed-ph": "Physics - Physics Education",
    "physics.flu-dyn": "Physics - Fluid Dynamics",
    "physics.gen-ph": "Physics - General Physics",
    "physics.geo-ph": "Physics - Geophysics",
    "physics.hist-ph": "Physics - History & Philosophy of Physics",
    "physics.ins-det": "Physics - Instrumentation & Detectors",
    "physics.med-ph": "Physics - Medical Physics",
    "physics.optics": "Physics - Optics",
    "physics.plasm-ph": "Physics - Plasma Physics",
    "physics.pop-ph": "Physics - Popular Physics",
    "physics.soc-ph": "Physics - Physics & Society",
    "physics.space-ph": "Physics - Space Physics",
    "stat.AP": "Statistics - Applications",
    "stat.CO": "Statistics - Computation",
    "stat.ME": "Statistics - Methodology",
    "stat.ML": "Statistics - Machine Learning",
    "stat.OT": "Statistics - Other",
    "stat.TH": "Statistics - Theory",
    "eess.AS": "Electrical Engineering - Audio, Speech & Language Processing",
    "eess.IV": "Electrical Engineering - Image & Video Processing",
    "eess.SP": "Electrical Engineering - Signal Processing",
    "eess.SY": "Electrical Engineering - Systems & Control",
    "q-bio.BM": "Quantitative Biology - Biomolecules",
    "q-bio.CB": "Quantitative Biology - Cell Behavior",
    "q-bio.GN": "Quantitative Biology - Genomics",
    "q-bio.MN": "Quantitative Biology - Molecular Networks",
    "q-bio.NC": "Quantitative Biology - Neurons & Cognition",
    "q-bio.OT": "Quantitative Biology - Other",
    "q-bio.PE": "Quantitative Biology - Populations & Evolution",
    "q-bio.QM": "Quantitative Biology - Quantitative Methods",
    "q-bio.SC": "Quantitative Biology - Subcellular Processes",
    "q-bio.TO": "Quantitative Biology - Tissues & Organs",
    "q-fin.CP": "Quantitative Finance - Computational Finance",
    "q-fin.EC": "Quantitative Finance - Economics",
    "q-fin.GN": "Quantitative Finance - General Finance",
    "q-fin.MF": "Quantitative Finance - Mathematical Finance",
    "q-fin.PM": "Quantitative Finance - Portfolio Management",
    "q-fin.PR": "Quantitative Finance - Pricing of Securities",
    "q-fin.RM": "Quantitative Finance - Risk Management",
    "q-fin.ST": "Quantitative Finance - Statistical Finance",
    "q-fin.TR": "Quantitative Finance - Trading & Market Microstructure",
    "nlin.AO": "Nonlinear Sciences - Adaptation & Self-Organizing Systems",
    "nlin.CD": "Nonlinear Sciences - Chaotic Dynamics",
    "nlin.CG": "Nonlinear Sciences - Cellular Automata & Lattice Gases",
    "nlin.PS": "Nonlinear Sciences - Pattern Formation & Solitons",
    "nlin.SI": "Nonlinear Sciences - Exactly Solvable & Integrable Systems",
    "econ.EM": "Economics - Econometrics",
    "econ.GN": "Economics - General Economics",
    "econ.TH": "Economics - Theory",
    "math-ph": "Mathematical Physics",
}

# Old/renamed categories
CATEGORY_LABELS.update(
    {
        "chao-dyn": "Chaotic Dynamics (now nlin.CD)",
        "q-alg": "Quantum Algebra (now math.QA)",
        "solv-int": "Exactly Solvable & Integrable Systems (now nlin.SI)",
        "alg-geom": "Algebraic Geometry (now math.AG)",
        "cmp-lg": "Computation & Language (now cs.CL)",
        "patt-sol": "Pattern Formation & Solitons (now nlin.PS)",
        "dg-ga": "Differential Geometry (now math.DG)",
        "adap-org": "Adaptation & Self-Organizing Systems (now nlin.AO)",
        "funct-an": "Functional Analysis (now math.FA)",
        "mtrl-th": "Materials Theory (now cond-mat.mtrl-sci)",
        "chem-ph": "Chemical Physics (now physics.chem-ph)",
        "comp-gas": "Cellular Automata & Lattice Gases (now nlin.CG)",
        "supr-con": "Superconductivity (now cond-mat.supr-con)",
        "atom-ph": "Atomic Physics (now physics.atom-ph)",
        "acc-phys": "Accelerator Physics (now physics.acc-ph)",
        "plasm-ph": "Plasma Physics (now physics.plasm-ph)",
        "ao-sci": "Atmospheric & Oceanic Science (now physics.ao-ph)",
        "bayes-an": "Bayesian Analysis",
    }
)


def readable_category(code):
    return CATEGORY_LABELS.get(code, code)


def readable_categories(category_str):
    codes = category_str.split()
    labels = [CATEGORY_LABELS.get(c, c) for c in codes]
    return " | ".join(labels)


def readable_column(col_name):
    names = {
        "id": "arXiv ID",
        "submitter": "Submitted by",
        "authors": "Authors",
        "title": "Title",
        "comments": "Comments",
        "journal-ref": "Journal Reference",
        "doi": "Digital Object Identifier (DOI)",
        "report-no": "Report Number",
        "categories": "Subject Categories",
        "license": "License",
        "abstract": "Abstract",
        "versions": "Version History",
        "update_date": "Last Updated",
        "authors_parsed": "Authors (structured)",
    }
    return names.get(col_name, col_name.replace("-", " ").replace("_", " ").title())


# ---------------------------------------------------------------------------
# Column descriptions (sourced from data_dictionary.yaml for source columns)
# ---------------------------------------------------------------------------
COLUMN_HELP = {
    # Source columns (from data_dictionary.yaml)
    "id": "Unique ArXiv paper identifier",
    "submitter": "Name of the person who submitted the paper to arXiv",
    "authors": "Comma-separated list of author names as plain text",
    "title": "Title of the paper",
    "comments": "Free-form comments field often containing page/figure counts or additional notes from the submitter",
    "journal-ref": "Journal reference for published papers",
    "doi": "Digital Object Identifier for the published version",
    "report-no": "Institutional report number assigned to the paper",
    "categories": "Space-separated list of arXiv category tags (primary and cross-list categories)",
    "license": "URL of the license under which the paper is distributed",
    "abstract": "Full text abstract of the paper",
    "versions": "Array of version records, each containing a version tag and creation timestamp",
    "update_date": "Date of the most recent version update, in YYYY-MM-DD format",
    "authors_parsed": "Parsed author names; each author is [last_name, first_names, suffix]",
    # Derived / computed columns
    "date": "Date of the most recent version update, parsed as a date",
    "year": "Year of the most recent version update",
    "month": "Month of the most recent version update (1–12)",
    "month_name": "Abbreviated month name",
    "n_cats": "Number of research categories assigned to a paper",
    "label": "Human-readable name for an arXiv category code",
    "categories_b": "Second research area in a co-occurrence pair",
    "full_name": "Author's full name constructed as first_name + last_name from authors_parsed",
    "license_short": "Shortened human-readable license category",
    "n_authors": "Number of authors listed on the paper",
    "n_auth_binned": "Number of authors, capped at 51 for display",
    "n_versions": "Number of versions (revisions) the paper has gone through",
    "n_vers_binned": "Number of versions, capped at 21 for display",
    "title_len": "Total characters in the paper title",
    "abstract_len": "Total characters in the abstract",
    "comments_len": "Total characters in the comments field",
    "has_pages": "Whether the comments field includes a page count",
    "has_figures": "Whether the comments field includes a figure count",
    "has_refs": "Whether the comments field includes a reference count",
    "domain": "Top-level arXiv domain (e.g. cs, math, physics)",
    "pct": "Author's paper count as a percentage of the top author in this category",
    "relative": "Author's paper count as a percentage of the most published author in the dataset",
    "count": "Number of papers or occurrences in the current grouping",
    "filled_pct": "Percentage of non-null (filled) values for this column",
    "papers": "Number of papers associated with this author, category, or domain",
    "subcategories": "Number of sub-categories within this domain",
    "_row_idx": "Internal row index for joining operations (not displayed)",
}


def strip_latex(text: str) -> str:
    return text or ""
